config/routes.rb
Rails.application.routes.draw do
  get '/game/try' => 'game#try'
  get '/game/reset'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def try

    if cookies[:counter] == nil
      cookies[:counter]=0
    end

    if cookies[:secret_num] == nil
      cookies[:secret_num]=rand(1..100)
    end

    @userguess=params[:userguess].to_i
    @secret_num=cookies[:secret_num].to_i

    case

    when @userguess>@secret_num
      @result="you guessed too high"

      cookies[:counter] = cookies[:counter].to_i + 1
      @counter = cookies[:counter]

    when @userguess<@secret_num
      @result="you guessed too low"

      cookies[:counter] = cookies[:counter].to_i + 1
      @counter = cookies[:counter]

    when @userguess==@secret_num
      @result="you win! the number was #{@secret_num}"
      cookies[:secret_num]=rand(1..100)
      @secret_num=cookies[:secret_num]
    end

  end

  def reset
    cookies[:counter] = 0
    @counter = cookies[:counter]

    params[]
    redirect_to '/game/try'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/try.html.erb
<h2>HiLo Game</h2>
<p>Type in a number from between 1 to 100 and see if you're correct!</p>

<form action="/game/try" method="get">
  <input type="number" name="userguess" placeholder="USERGUESS" required/>
  <input type="submit" name="" value="submit" /> <br><br>
  <!-- <button type="button" onclick="">RESET COUNTER</button> -->
</form>
<%= button_to 'RESET COUNTER', game_reset_path, method: :get %>
<br>
<%= @counter %>

<br><br>

<%= @result %>

<div class="img_container">
  <img src="/Users/learn/Desktop/HiLo/app/assets/images/sunset.jpg"  />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HiLo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>